package com.persiqa;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

import com.persiqa.model.Ckm.Context;
import com.persiqa.model.Ckm.Entity;
import com.persiqa.model.Ckm.Kind;
import com.persiqa.model.Ckm.KnowledgeKind;
import com.persiqa.model.Ckm.Relation;
import com.persiqa.model.Ckm.RelationType;
import com.persiqa.model.Ckm.State;
import com.persiqa.model.Ckm.Statement;
import com.persiqa.persistence.JpaCanonicalStore;
import com.persiqa.persistence.repository.CanonicalizationRepository;
import com.persiqa.persistence.repository.DerivationRepository;
import com.persiqa.persistence.repository.RepresentationRepository;
import com.persiqa.persistence.repository.StateRepository;
import com.persiqa.persistence.repository.StatementContextRepository;
import java.time.Instant;
import java.util.Map;
import java.util.Set;
import java.util.UUID;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;

/** Exercises the JPA adapter against the H2 schema generated by the application profile. */
@SpringBootTest
@ActiveProfiles("dev")
class JpaCanonicalStoreIntegrationTest {
  @Autowired private JpaCanonicalStore store;
  @Autowired private StatementContextRepository contexts;
  @Autowired private DerivationRepository derivations;
  @Autowired private CanonicalizationRepository canonicalizations;
  @Autowired private StateRepository states;
  @Autowired private RepresentationRepository representations;

  @Test
  void persists_the_statement_first_electrical_model_without_losing_semantics() {
    var scope = UUID.randomUUID();
    store.createScope(scope, "electrical-test");
    var breaker = new Entity("MCB-01");
    var outlet = new Entity("Outlet-01");
    var supplies =
        new RelationType("supplies", Set.of(Kind.ENTITY), Set.of(Kind.ENTITY), false, "none", true);
    var first = new Relation("supply-a", supplies, breaker, outlet);
    var second = new Relation("supply-b", supplies, breaker, outlet);

    var firstId = store.save(scope, first);
    var secondId = store.save(scope, second);
    assertNotEquals(firstId, secondId);
    assertEquals(first, store.findRelation(scope, "supply-a"));

    var context =
        new Context(
            "inspection-42",
            0.9,
            Instant.parse("2026-01-01T10:00:00Z"),
            Instant.parse("2026-01-01T00:00:00Z"),
            Instant.parse("2026-01-02T00:00:00Z"),
            "as-built");
    var asserted =
        new Statement(
            "assertion-a", KnowledgeKind.EXPLICIT, "supplies", breaker, outlet, Set.of(), context);
    store.save(scope, asserted);
    store.appendContext(scope, "assertion-a", new Context("reinspection", 0.8, "as-maintained"));
    store.canonicalize(scope, asserted, first, "SUPPORTS", "statement-first-v0.1");

    var derived =
        new Statement(
            "derived-a",
            KnowledgeKind.DERIVED,
            "supplies",
            breaker,
            outlet,
            Set.of("supply-a", "supply-b"),
            context);
    store.save(scope, derived);

    var restored = store.findStatement(scope, "derived-a");
    assertNotNull(restored);
    assertEquals(KnowledgeKind.DERIVED, restored.knowledgeKind());
    assertEquals(Set.of("supply-a", "supply-b"), restored.derivedFrom());
    assertEquals("inspection-42", restored.context().provenance());
    assertEquals(Instant.parse("2026-01-02T00:00:00Z"), restored.context().validTo());
    assertEquals(2, store.findContexts(scope, "assertion-a").size());
    assertEquals(2, contexts.findByStatementIdOrderById(store.save(scope, asserted)).size());
    assertEquals(2, derivations.findByStatementId(store.save(scope, derived)).size());
    assertEquals(1, canonicalizations.findByStatementId(store.save(scope, asserted)).size());
  }

  @Test
  void persists_state_ownership_through_the_has_state_contract() {
    var scope = UUID.randomUUID();
    store.createScope(scope, "state-test");
    var breaker = new Entity("RCBO-01");
    var relation =
        new Relation(
            "state-a",
            new RelationType(
                "hasState",
                Set.of(Kind.ENTITY, Kind.RELATION),
                Set.of(Kind.STATE),
                false,
                "none",
                false),
            breaker,
            new State("Closed"));

    store.save(scope, relation);
    assertEquals(1, states.count());
  }

  @Test
  void keeps_representation_metadata_outside_the_canonical_model() {
    var scope = UUID.randomUUID();
    store.createScope(scope, "representation-test");
    store.saveRepresentation(
        scope, UUID.randomUUID(), "Electrical view", Map.of(), Map.of("layout", "grid"));
    assertEquals(1, representations.count());
  }
}
