package com.persiqa;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertThrows;

import com.persiqa.model.Ckm.Concept;
import com.persiqa.model.Ckm.Context;
import com.persiqa.model.Ckm.Entity;
import com.persiqa.model.Ckm.Kind;
import com.persiqa.model.Ckm.KnowledgeKind;
import com.persiqa.model.Ckm.Relation;
import com.persiqa.model.Ckm.RelationType;
import com.persiqa.model.Ckm.State;
import com.persiqa.model.Ckm.Statement;
import com.persiqa.persistence.JpaCanonicalStore;
import com.persiqa.persistence.repository.CanonicalObjectRepository;
import com.persiqa.persistence.repository.CanonicalizationRepository;
import com.persiqa.persistence.repository.DerivationRepository;
import com.persiqa.persistence.repository.RepresentationRepository;
import com.persiqa.persistence.repository.StateRepository;
import com.persiqa.persistence.repository.StatementContextRepository;
import jakarta.persistence.EntityManagerFactory;
import java.math.BigDecimal;
import java.time.Instant;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.UUID;
import org.hibernate.SessionFactory;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;

/** Exercises the JPA adapter against the H2 schema generated by the application profile. */
@SpringBootTest
@ActiveProfiles("dev")
class JpaCanonicalStoreIntegrationTest {
  @Autowired private JpaCanonicalStore store;
  @Autowired private CanonicalObjectRepository objects;
  @Autowired private StatementContextRepository contexts;
  @Autowired private DerivationRepository derivations;
  @Autowired private CanonicalizationRepository canonicalizations;
  @Autowired private StateRepository states;
  @Autowired private RepresentationRepository representations;
  @Autowired private EntityManagerFactory entityManagerFactory;

  @Test
  void allocates_identity_ordinals_from_a_scope_local_counter() {
    var scope = UUID.randomUUID();
    store.createScope(scope, "identity-counter-test", "test");

    var prefix = "stmt-supply-explicit";
    store.save(scope, new Entity(prefix + "-001"));

    assertEquals(2L, store.nextIdentityOrdinal(scope, prefix));
    assertEquals(3L, store.nextIdentityOrdinal(scope, prefix));
    assertEquals(1L, store.nextIdentityOrdinal(scope, "rel-supply"));
  }

  @Test
  void reads_a_relation_page_with_a_bounded_number_of_queries() {
    var scope = UUID.randomUUID();
    store.createScope(scope, "relation-page-query-test", "test");
    var supplies =
        new RelationType("supplies", Set.of(Kind.ENTITY), Set.of(Kind.ENTITY), false, "none", true);
    var source = new Entity("source");
    for (var ordinal = 1; ordinal <= 30; ordinal++) {
      store.save(
          scope,
          new Relation("supply-" + ordinal, supplies, source, new Entity("target-" + ordinal)));
    }

    var statistics = entityManagerFactory.unwrap(SessionFactory.class).getStatistics();
    statistics.setStatisticsEnabled(true);
    statistics.clear();

    var page = store.findRelations(scope, new com.persiqa.core.PageQuery(0, 25, null));

    assertEquals(25, page.content().size());
    org.junit.jupiter.api.Assertions.assertTrue(
        statistics.getPrepareStatementCount() <= 8,
        () -> "relation page used " + statistics.getPrepareStatementCount() + " SQL statements");
  }

  @Test
  void reads_a_relation_type_subgraph_without_loading_other_relation_types() {
    var scope = UUID.randomUUID();
    store.createScope(scope, "typed-subgraph-test", "test");
    var source = new Entity("source");
    var target = new Entity("target");
    var supplies =
        new RelationType("supplies", Set.of(Kind.ENTITY), Set.of(Kind.ENTITY), false, "none", true);
    var dependsOn =
        new RelationType(
            "dependsOn", Set.of(Kind.ENTITY), Set.of(Kind.ENTITY), false, "none", true);
    var supply = new Relation("supply-source-target", supplies, source, target);
    store.save(scope, supply);
    store.save(scope, new Relation("dependency-source-target", dependsOn, source, target));
    var statement =
        new Statement(
            "supply-statement",
            KnowledgeKind.EXPLICIT,
            "supplies",
            source,
            target,
            Set.of(),
            Context.unspecified());
    store.save(scope, statement);
    store.canonicalize(scope, statement, supply, "ASSERTS", "statement-first-v0.1");

    var subgraph = store.findRelationsByType(scope, "supplies");

    assertEquals(List.of(supply), subgraph);
    assertEquals(List.of(statement), store.findStatementsForRelations(scope, subgraph));
  }

  @Test
  void persists_the_statement_first_electrical_model_without_losing_semantics() {
    var scope = UUID.randomUUID();
    store.createScope(scope, "electrical-test", "test");
    var breaker = new Entity("MCB-01");
    var outlet = new Entity("Outlet-01");
    var supplies =
        new RelationType("supplies", Set.of(Kind.ENTITY), Set.of(Kind.ENTITY), false, "none", true);
    var first = new Relation("supply-a", supplies, breaker, outlet);
    var second = new Relation("supply-b", supplies, breaker, outlet);

    var firstId = store.save(scope, first);
    var secondId = store.save(scope, second);
    assertNotEquals(firstId, secondId);
    assertEquals(first, store.findRelation(scope, "supply-a"));

    var context =
        new Context(
            "inspection-42",
            new BigDecimal("0.9"),
            Instant.parse("2026-01-01T10:00:00Z"),
            Instant.parse("2026-01-01T00:00:00Z"),
            Instant.parse("2026-01-02T00:00:00Z"),
            "as-built");
    var asserted =
        new Statement(
            "assertion-a", KnowledgeKind.EXPLICIT, "supplies", breaker, outlet, Set.of(), context);
    store.save(scope, asserted);
    store.appendContext(
        scope, "assertion-a", new Context("reinspection", new BigDecimal("0.8"), "as-maintained"));
    var overwritten =
        new Statement(
            "assertion-a",
            KnowledgeKind.EXPLICIT,
            "supplies",
            breaker,
            outlet,
            Set.of(),
            new Context("conflicting-source", new BigDecimal("0.7"), "as-built"));
    assertThrows(IllegalArgumentException.class, () -> store.save(scope, overwritten));
    store.canonicalize(scope, asserted, first, "SUPPORTS", "statement-first-v0.1");

    var derived =
        new Statement(
            "derived-a",
            KnowledgeKind.DERIVED,
            "supplies",
            breaker,
            outlet,
            Set.of("supply-a", "supply-b"),
            context);
    store.save(scope, derived);

    var restored = store.findStatement(scope, "derived-a");
    assertNotNull(restored);
    assertEquals(KnowledgeKind.DERIVED, restored.knowledgeKind());
    assertEquals(Set.of("supply-a", "supply-b"), restored.derivedFrom());
    assertEquals("inspection-42", restored.context().provenance());
    assertEquals(Instant.parse("2026-01-02T00:00:00Z"), restored.context().validTo());
    assertEquals("inspection-42", store.findContexts(scope, "derived-a").getFirst().provenance());
    assertEquals(
        Instant.parse("2026-01-02T00:00:00Z"),
        store.findContexts(scope, "derived-a").getFirst().validTo());
    assertEquals(2, store.findContexts(scope, "assertion-a").size());
    assertEquals(
        2, contexts.findByStatementIdOrderByRecordedAtAscIdAsc(store.save(scope, asserted)).size());
    assertEquals(2, derivations.findByStatementId(store.save(scope, derived)).size());
    assertEquals(1, canonicalizations.findByStatementId(store.save(scope, asserted)).size());
  }

  @Test
  void persists_state_ownership_through_the_has_state_contract() {
    var scope = UUID.randomUUID();
    store.createScope(scope, "state-test", "test");
    var breaker = new Entity("RCBO-01");
    var closed = new State("Closed");
    var relation =
        new Relation(
            "state-a",
            new RelationType(
                "hasState",
                Set.of(Kind.ENTITY, Kind.RELATION),
                Set.of(Kind.STATE),
            false,
            "none",
            false),
            breaker,
            closed);

    store.save(scope, relation);
    var stateId = objects.findByScopeIdAndIdentityKey(scope, closed.id()).orElseThrow().id();
    assertEquals(1, states.findAllById(Set.of(stateId)).size());
  }

  @Test
  void keeps_representation_metadata_outside_the_canonical_model() {
    var scope = UUID.randomUUID();
    store.createScope(scope, "representation-test", "test");
    var representationId = UUID.randomUUID();
    store.saveRepresentation(
        scope, representationId, "Electrical view", Map.of(), Map.of("layout", "grid"));
    assertEquals(true, representations.findById(representationId).isPresent());
  }

  @Test
  void persists_the_electrical_refinement_without_replacing_the_coarse_model() {
    var scope = UUID.randomUUID();
    var breaker = new Entity("MCB-01");
    var outlet = new Entity("Outlet-01");
    var cable = new Entity("Cable-17");
    var junctionBox = new Entity("JunctionBox-03");
    var supplies =
        new RelationType("supplies", Set.of(Kind.ENTITY), Set.of(Kind.ENTITY), false, "none", true);
    var coarse = new Relation("supply-summary", supplies, breaker, outlet);
    var firstSegment = new Relation("supply-segment-1", supplies, breaker, cable);
    var secondSegment = new Relation("supply-segment-2", supplies, cable, junctionBox);

    store.createScope(scope, "electrical-refinement-test", "test");
    store.save(scope, coarse);
    store.save(scope, firstSegment);
    store.save(scope, secondSegment);
    store.save(
        scope,
        new Statement(
            "supply-refinement",
            KnowledgeKind.DERIVED,
            "supplies",
            breaker,
            outlet,
            Set.of("supply-segment-1", "supply-segment-2"),
            new Context("topology-analysis", new BigDecimal("0.95"), "as-built")));

    assertEquals(coarse, store.findRelation(scope, "supply-summary"));
    assertEquals(firstSegment, store.findRelation(scope, "supply-segment-1"));
    assertEquals(
        Set.of("supply-segment-1", "supply-segment-2"),
        store.findStatement(scope, "supply-refinement").derivedFrom());
  }

  @Test
  void persists_kubernetes_identity_across_role_and_state_changes() {
    var scope = UUID.randomUUID();
    var vm = new Entity("VM-01");
    var playsRole =
        new RelationType(
            "playsRole", Set.of(Kind.ENTITY), Set.of(Kind.CONCEPT), false, "none", false);
    var hasState =
        new RelationType(
            "hasState",
            Set.of(Kind.ENTITY, Kind.RELATION),
            Set.of(Kind.STATE),
            false,
            "none",
            false);
    var kubernetesNode =
        new Relation("kubernetes-node", playsRole, vm, new Concept("KubernetesNode"));
    var buildRunner = new Relation("build-runner", playsRole, vm, new Concept("BuildRunner"));
    var running = new Relation("running", hasState, vm, new State("Running"));
    var stopped = new Relation("stopped", hasState, vm, new State("Stopped"));

    store.createScope(scope, "kubernetes-identity-test", "test");
    store.save(scope, kubernetesNode);
    store.save(scope, running);
    store.save(scope, buildRunner);
    store.save(scope, stopped);

    assertEquals("VM-01", store.findRelation(scope, "kubernetes-node").source().id());
    assertEquals("VM-01", store.findRelation(scope, "build-runner").source().id());
    assertEquals("Running", store.findRelation(scope, "running").target().id());
    assertEquals("Stopped", store.findRelation(scope, "stopped").target().id());
  }

  @Test
  void preserves_competing_statement_evidence_and_rejects_invalid_relation_endpoints() {
    var scope = UUID.randomUUID();
    var breaker = new Entity("Breaker-01");
    var outletA = new Entity("Outlet-A");
    var outletB = new Entity("Outlet-B");

    store.createScope(scope, "competing-evidence-test", "test");
    store.save(
        scope,
        new Statement(
            "inspection-a",
            KnowledgeKind.EXPLICIT,
            "supplies",
            breaker,
            outletA,
            Set.of(),
            new Context("inspection-A", new BigDecimal("0.8"), "T1")));
    store.save(
        scope,
        new Statement(
            "inspection-b",
            KnowledgeKind.EXPLICIT,
            "supplies",
            breaker,
            outletB,
            Set.of(),
            new Context("inspection-B", new BigDecimal("0.7"), "T1")));

    assertEquals("Outlet-A", ((Entity) store.findStatement(scope, "inspection-a").object()).id());
    assertEquals("Outlet-B", ((Entity) store.findStatement(scope, "inspection-b").object()).id());
    assertThrows(
        IllegalArgumentException.class,
        () ->
            store.save(
                scope,
                new Relation(
                    "invalid-state",
                    new RelationType(
                        "hasState",
                        Set.of(Kind.ENTITY),
                        Set.of(Kind.STATE),
                        false,
                        "none",
                        false),
                    breaker,
                    outletA)));
  }
}
